describe('RootLayout Metadata', () => {
  it('メタデータのタイトルが設定される予定', () => {
    // レッド状態：メタデータが更新されていない状態をテスト
    const expectedTitle = '医療シミュレーター'
    const expectedDescription = '医療トレーニングのためのシミュレーションアプリケーション'
    
    // 現在のメタデータはまだ更新されていない
    const currentTitle = 'Create Next App'
    const currentDescription = 'Generated by create next app'
    
    expect(currentTitle).not.toBe(expectedTitle)
    expect(currentDescription).not.toBe(expectedDescription)
  })

  it('メタデータの説明文が設定される予定', () => {
    // この時点では古いメタデータが設定されている
    const expectedDescription = '医療トレーニングのためのシミュレーションアプリケーション'
    const currentDescription = 'Generated by create next app'
    
    expect(currentDescription).not.toBe(expectedDescription)
  })
})